language: php

php:
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev

notifications:
  email:
    - desperado@minsk-info.ru

script: ./vendor/bin/phpunit --bootstrap ./Tests/bootstrap.php --configuration ./phpunit.xml.dist  --coverage-text
